### ISSUE TITLE
Missing Fritzing file?

### ISSUE THREAD

**Issue by erichiggins** [sparkfun/ATX_Power_Connector_Breakout#1]
Is there a Fritzing file available for this breakout board? I'm not seeing it within the Fritzing parts library.

**Comment by bboyho** [comment]
Hi!

Hmm, looking at our [Fritzing parts repository](https://github.com/sparkfun/Fritzing_Parts/tree/main/products), I don't believe we have made one for that specific part yet. This seems like a simple part, I might have some time to make the part within the next month.

I'll have to place the design files through the Eagle-to-Fritzing converter and see what happens.

**Comment by erichiggins** [comment]
Appreciate the help, thank you!

**Comment by bboyho** [comment]
The Eagle-to-Fritzing converter spit out some of the board. I had to manually add some PTHs and pads to make it functional for all layers. I added some 5mm screw terminals in the breadboard but kept the ATX connector off since there was a horizontal and vertical part. Other than that, it should be functional. =)

https://github.com/sparkfun/Fritzing_Parts/blob/main/products/15035-sfe_ATX_Power_Connector_Breakout_12V_5V_Power_Supply.fzpz
